"""
Pydantic schemas package.

Schemas define the validated structures exchanged via the API.
"""

from app.schemas.ai import AIChatRequest, AIChatResponse
from app.schemas.analytics import (
    AnalyticsCSVResponse,
    AnalyticsSnapshot,
    CareReport,
    SnapshotNotification,
    SnapshotSummary,
    TrendSeries,
    WeeklySummary,
)
from app.schemas.art import ArtGenerationRequest, ArtGenerationResponse
from app.schemas.auth import LoginRequest, LogoutRequest, RefreshRequest, SignupRequest, TokenResponse
from app.schemas.finance import EarnRequest, FinanceResponse, FinanceSummary, InventoryEntry, LeaderboardEntry, PurchaseItem, PurchaseRequest, TransactionRecord
from app.schemas.game import GameLeaderboardEntry, GameLeaderboardResponse, GamePlayRequest, GamePlayResponse, GameReward
from app.schemas.next_gen import (
    ARSessionResponse,
    CloudSavePayload,
    CloudSaveResponse,
    HabitPredictionResponse,
    SeasonalEventResponse,
    SocialInteractionRequest,
    SocialInteractionResponse,
    VoiceCommandRequest,
    VoiceCommandResponse,
    WeatherReactionResponse,
)
from app.schemas.pet import (
    PetAIInsights,
    PetCommandRequest,
    PetCommandResponse,
    PetCreate,
    PetHelpResponse,
    PetInteractRequest,
    PetNotification,
    PetRead,
    PetStats,
    PetUpdate,
)
from app.schemas.profile import AvatarUpdateRequest, AvatarUploadResponse, Preferences, ProfileCreate, ProfileResponse, ProfileUpdate
from app.schemas.quest import (
    ActiveQuestsResponse,
    CoachAdviceResponse,
    CoachInsight,
    QuestCompletionRequest,
    QuestCompletionResponse,
    QuestCompletionResult,
    QuestRead,
    QuestReward,
)
from app.schemas.social import (
    FriendListEntry,
    FriendRequestPayload,
    FriendRespondPayload,
    FriendsListResponse,
    LeaderboardEntry as SocialLeaderboardEntry,
    LeaderboardResponse,
    PublicProfileSummary,
    PublicProfilesResponse,
)
from app.schemas.sync import CloudSyncState, SyncFetchResponse, SyncPushRequest, SyncPushResponse

__all__ = [
    "PetAIInsights",
    "PetCommandRequest",
    "PetCommandResponse",
    "PetCreate",
    "PetHelpResponse",
    "PetInteractRequest",
    "PetNotification",
    "PetRead",
    "PetStats",
    "PetUpdate",
    "ProfileCreate",
    "ProfileUpdate",
    "ProfileResponse",
    "AvatarUploadResponse",
    "Preferences",
    "AvatarUpdateRequest",
    "SignupRequest",
    "LoginRequest",
    "RefreshRequest",
    "LogoutRequest",
    "TokenResponse",
    "AIChatRequest",
    "AIChatResponse",
    "ArtGenerationRequest",
    "ArtGenerationResponse",
    "TransactionRecord",
    "InventoryEntry",
    "PurchaseItem",
    "PurchaseRequest",
    "EarnRequest",
    "FinanceSummary",
    "FinanceResponse",
    "LeaderboardEntry",
    "AnalyticsSnapshot",
    "AnalyticsCSVResponse",
    "CareReport",
    "TrendSeries",
    "WeeklySummary",
    "SnapshotSummary",
    "SnapshotNotification",
    "GamePlayRequest",
    "GamePlayResponse",
    "GameReward",
    "GameLeaderboardEntry",
    "GameLeaderboardResponse",
    "SocialInteractionRequest",
    "SocialInteractionResponse",
    "VoiceCommandRequest",
    "VoiceCommandResponse",
    "ARSessionResponse",
    "CloudSavePayload",
    "CloudSaveResponse",
    "WeatherReactionResponse",
    "HabitPredictionResponse",
    "SeasonalEventResponse",
    "FriendRequestPayload",
    "FriendRespondPayload",
    "FriendListEntry",
    "FriendsListResponse",
    "PublicProfileSummary",
    "PublicProfilesResponse",
    "SocialLeaderboardEntry",
    "LeaderboardResponse",
    "QuestRead",
    "QuestReward",
    "ActiveQuestsResponse",
    "QuestCompletionRequest",
    "QuestCompletionResponse",
    "QuestCompletionResult",
    "CoachAdviceResponse",
    "CoachInsight",
    "SyncFetchResponse",
    "SyncPushRequest",
    "SyncPushResponse",
    "CloudSyncState",
]

