/**
 * API client for analytics feature
 * Handles fetching analytics snapshots, weekly summaries, and CSV exports
 * Analytics data is generated by backend aggregation logic
 */
import { apiRequest } from './httpClient';
import type { AnalyticsCSVResponse, AnalyticsSnapshot, WeeklySummary } from '../types/analytics';

const API_BASE = '/api/analytics';

export async function fetchSnapshot(): Promise<AnalyticsSnapshot> {
  // Analytics snapshots require backend aggregation logic
  // No mock fallback - must use backend API
  try {
    return await apiRequest<AnalyticsSnapshot>(`${API_BASE}/snapshot`);
  } catch (error) {
    console.error('Analytics API unavailable', error);
    throw new Error('Failed to load analytics. Please ensure the backend server is running and try again.');
  }
}

export async function fetchWeeklySummary(endDate?: string): Promise<WeeklySummary> {
  const url = endDate ? `${API_BASE}/daily?end_date=${encodeURIComponent(endDate)}` : `${API_BASE}/daily`;
  return apiRequest<WeeklySummary>(url);
}

export async function exportReports(start: string, end: string): Promise<AnalyticsCSVResponse> {
  const url = `${API_BASE}/export?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`;
  const response = await apiRequest<{ filename: string; content: string }>(url);
  return {
    filename: response.filename || `care-report-${start}-to-${end}.csv`,
    content: response.content,
  };
}

